name: Deploy Docs

on:
  push:
    branches:
      - main # 主分支名称，根据你的实际情况修改
    paths:
      - docs/**
      - package.json
      - package-lock.json
      - docs/.vitepress/config.js
  # 允许你从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:
# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm install
      - run: npm run docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
          force_orphan: true
          # cname: # 如果你有自定义域名，可以在这里设置
